library(here)
library(ProjectTemplate)
library(tidyverse)
library(tidymodels)
library(readr)
library(skimr)
library(glmnet)
library(pROC)
library(yardstick)
library(pins)

base_dir <- here::here()
data_dir <- file.path(base_dir, "MAS8600_Dataset")
here::here()
list.files(data_dir)
